### ISSUE TITLE
Proposal: Add compaction support to RowContainer

### ISSUE THREAD

**Issue by usurai** [facebookincubator/velox#7534]
### Description

Part of https://github.com/facebookincubator/velox/issues/7180 to support spilling partial state.

`RowContainer` is backed by a set of memory allocations. Compaction selects some of the allocations as target, moves rows located in these target allocations to free space of other allocations, then free the target allocations. When selecting the targets, it tries to maximize the freeable space.
The compaction API returns `[freedBytes, updatedRows]`, with `freedBytes` being freed space size, and `updatedRows` being a map from moved rows' original ptr to the updated ptr, to enable the caller to update the reference to rows.

### Defragmentation Strategy:
We mainly focus on moving out contiguous allocations: iterate each large allocation starting from the largest one, if it can be absorbed by the rest of allocations(non-contiguous included), add it to the target set.
Only contiguous allocations are considered candidate for the target, non-contiguous allocations don't get moved: Since freeing non-contiguous only gives at most 256KB, which is negligible.

### Detailed implementation:
- Construct stats of allocations for selecting: size of the allocation, and free space: the size of free rows in this allocation plus the unused space if it's the last allocation.
- Sort large allocations by `{size, free_space}` in decreasing order, then iterate over the sorted allocations: if `total_free_space - free_space[i] >= size[i] - free_space[i]`, add allocation `i` to the target set, and `total_free_space -= free_space[i]`.
- Move rows: get target rows by `listRows` in target allocations, and move them to the following while recording the change in `upadtedRows`.
    1. free rows of the rest of allocations
    2. unused space of the rest of allocation, if any.
- Free target allocations.

Following struct / functionalities are needed to support the feature:
- `struct AllocationCompactionStat`: allocation's index, kind, size, free space.
- `vector<AllocationCompactionStat> RowContainer::getCompactionStats()`: private method that builds stats for all allocation. It gets allocations' addr, size from `AllocationPool`, then for each free row, determine which allocation it's in, mark allocation id in row and update free space in `AllocationCompactionStat`.
- `RowContainer::listRows` that supports only list rows within certain allocation.
- `AllocationPool::freeRanges(std::vector<int32_t> indices)`: To free target allocations from `AllocationPool`.

### Tasks

- [ ] `struct AllocationCompactionStat`, `RowContainer::getCompactionStats()` and tests.
- [ ] `RowContainer::listRows` that supports only list rows within one allocation and tests.
- [ ] `AllocationPool::freeRanges(std::vector<int32_t> indices)` and tests.
- [ ] `RowContainer::compact()` and tests.

**Comment by usurai** [comment]
@mbasmanova Thanks for replying!
Sorry I didn't clarify the proposal was only targeted to `AllocationPool` used for fixed-size rows memory.
I overlooked `HashStringAllocator` as I thought it has its own mechanism to free to pool(turns out it's only for allocations directly from pool😥). And yeah, the `HashStringAllocator` part should be the key if the row contains string/complex types. I think I need to do some research on this and update this thread then.
Will let you know when this is ready. Thanks!

**Comment by usurai** [comment]
Hi @mbasmanova, I've updated the proposal with `HashStringAllocator` compaction, please take a look. Thanks!

**Comment by mbasmanova** [comment]
@usurai Thank you for updating the proposal. Overall looks good % we need to come up with a test that help us evaluate the effectiveness of the proposed algorithms and tweak these if needed. 

(Going forward, let's use Google Docs or similar to allow for each inline commenting.)

**Comment by usurai** [comment]
@mbasmanova
Google doc version: https://docs.google.com/document/d/11bsoVSPVjCS4yCoKmUAFIgy_xu9bUwsKzZ6dKHtnW5Q/edit?usp=sharing
My thought on testing is in `Test Strategy` section. Thanks!
